
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

cloud:

# Text to speech
tts:
  - platform: google_translate
  
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.20.0.4 ###(Nginx Proxy Manager LXC IP)###

pyscript: !include pyscript/config.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
homeassistant:
  packages: !include_dir_named packages