sensor:
  - platform: sonarr_upcoming_media
    api_key: !secret sonarr_key
    host: !secret sonarr_host
  - platform: radarr_upcoming_media
    api_key: !secret radarr_key
    host: !secret radarr_host
  - platform: time_date
    display_options:
      - "time"
      - "time_utc"
      - "date"
  - platform: mqtt_room
    name: "Christian's iPhone BLE"
    device_id: !secret cb_iphone_ble_id
    state_topic: !secret cb_iphone_ble_topic
    timeout: 5
    away_timeout: 120
  - platform: mqtt_room
    name: "Christian's Watch BLE"
    device_id: !secret cb_watch_ble_id
    state_topic: !secret cb_watch_ble_topic
    timeout: 5
    away_timeout: 120
  - platform: mqtt_room
    name: "Carley's iPhone BLE"
    device_id: !secret cf_iphone_ble_id
    state_topic: !secret cf_iphone_ble_topic
    timeout: 5
    away_timeout: 120
  - platform: mqtt_room
    name: "Ally's iPhone BLE"
    device_id: !secret ab_iphone_ble_id
    state_topic: !secret ab_iphone_ble_topic
    timeout: 5
    away_timeout: 120
  - platform: mqtt_room
    name: "Kelly's iPhone BLE"
    device_id: !secret kb_iphone_ble_id
    state_topic: !secret kb_iphone_ble_topic
    timeout: 5
    away_timeout: 120
